services:
  cicd-books-api-service:
    build: ./api
    volumes:
      - ./api/server.js:/app/server.js
    networks:
      - books-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - cicd-books-api-service
    networks:
      - books-net

networks:
  books-net:
    driver: bridge