name: Docker
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  # lehetővé teszi, hogy "kézzel" elindítsam a folyamatot
  workflow_dispatch:
 
permissions:
  contents: write
 
jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
 
    - name: Checkout repository
      uses: actions/checkout@v4
 
    - name: Log in to GHCR
      run: docker login ghcr.io -u wafflsett -p ${{ secrets.GHCR_TOKEN }}
 
    - name: Build and push image
      run: |
        docker compose build
        docker tag cicd-books-frontend ghcr.io/wafflsett/cicd-books:$IMAGE_TAG
        docker push ghcr.io/wafflsett/cicd-books:$IMAGE_TAG
 
    - name: Update deployment manifest and apply
      run: |
        sed -i 's|image: ghcr.io/wafflsett/cicd-books:latest|image: ghcr.io/wafflsett/cicd-books:'"$IMAGE_TAG"'|' test-deployment.yaml
 
        mkdir -p ~/.kube
        echo "${{ secrets.JEDLIK_K8S_CONFIG }}" | base64 -d > ~/.kube/config
        kubectl apply -f ./test-deployment.yaml