name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: docker login ghcr.io -u wafflsett -p ${{ secrets.GHCR_TOKEN }}

    - name: Build and push API image
      run: |
        docker build ./api -t ghcr.io/wafflsett/cicd-books-api:$IMAGE_TAG
        docker push ghcr.io/wafflsett/cicd-books-api:$IMAGE_TAG

    - name: Build and push Frontend image
      run: |
        docker build ./frontend -t ghcr.io/wafflsett/cicd-books-frontend:$IMAGE_TAG
        docker push ghcr.io/wafflsett/cicd-books-frontend:$IMAGE_TAG

    - name: Update deployment manifest and apply
      run: |
        sed -i "s|image: ghcr.io/wafflsett/cicd-books-api:latest|image: ghcr.io/wafflsett/cicd-books-api:$IMAGE_TAG|" test-deployment.yaml
        sed -i "s|image: ghcr.io/wafflsett/cicd-books-frontend:latest|image: ghcr.io/wafflsett/cicd-books-frontend:$IMAGE_TAG|" test-deployment.yaml

        mkdir -p ~/.kube
        echo "${{ secrets.JEDLIK_K8S_CONFIG }}" | base64 -d > ~/.kube/config
        kubectl apply -f ./test-deployment.yaml